### ISSUE TITLE
ERROR: type Plot2D has no field markers

### ISSUE THREAD

**Issue by cjruiz** [ma-laforge/InspectDR.jl#10]
i'm get this error with this code:

using Plots; inspectdr()

plot(1)

any idea?

**Comment by ma-laforge** [comment]
Sounds like you are running an old version of Plots.jl.

At this point in time, you should be running the following to ensure things work properly:
Julia v0.6 / Plots.jl v0.12.1 / InspectDR v0.2.3

I suggest updating your Julia session:
```
Pkg.update()
```

And possibly "freeing" your version of Plots.jl if you have previously "pinned" it to an old version:
```
Pkg.free("Plots")
```
