### ISSUE TITLE
Window icons (minimize and maximize) missing

### ISSUE THREAD

**Issue by w1res** [ma-laforge/InspectDR.jl#17]
I'm using Windows 10. It looks like the icons are wrong or missing for the window controls. The "X" to close the window looks OK, but the minimize and maximize look like some kind of generic image default. See the picture below:

![image](https://user-images.githubusercontent.com/2823875/47328139-d8982980-d63d-11e8-9387-58c163d5e38f.png)

I'm using a 4K display, not sure if that makes a difference.

**Comment by ma-laforge** [comment]
Strange, but it sounds like a problem with Gtk.jl to me (or maybe even the core libraries themselves).

Do you still have the same problem if you run:
```
using Gtk

wnd = Gtk.Window("A window", 640, 480, true)
```

If so, I would raise the issue here:
https://github.com/JuliaGraphics/Gtk.jl/issues

**Comment by w1res** [comment]
> Do you still have the same problem if you run:
> 
> ```
> using Gtk
> 
> wnd = Gtk.Window("A window", 640, 480, true)
> ```
> 
> If so, I would raise the issue here:
> https://github.com/JuliaGraphics/Gtk.jl/issues

I ran the commands you said and still have the issue. I will check in the Gtk project.

Thanks.
