### ISSUE TITLE
DEFAULTS_INSPECTDR[:fontname] not working

### ISSUE THREAD

**Issue by ma-laforge** [ma-laforge/InspectDR.jl#20]
Appears that the `getstyle()` function uses `DEFAULT_FONTNAME` instead of the `fontname` parameter provided.

**Comment by ma-laforge** [comment]
Fixed in https://github.com/ma-laforge/InspectDR.jl/commit/b869eae6b178683a12a22f3d36d8344a35641cfb

Waiting to tag a release.

**Comment by ufechner7** [comment]
There was a new release since the fix. Can it be closed?

**Comment by ma-laforge** [comment]
Yes. Thanks.
